-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 12:32:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lf_dawii
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lf_dawii
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lf_dawii` ;
USE `lf_dawii` ;

-- -----------------------------------------------------
-- Table `lf_dawii`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lf_dawii`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lf_dawii`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lf_dawii`.`Status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lf_dawii`.`Kind`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lf_dawii`.`Kind` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lf_dawii`.`Priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lf_dawii`.`Priority` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lf_dawii`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lf_dawii`.`Project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lf_dawii`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lf_dawii`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `is_active` INT NOT NULL,
  `kind` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lf_dawii`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lf_dawii`.`Ticket` (
  `id` INT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `kind_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `asigned_id` INT NULL,
  `project_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `priority_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`kind_id` ASC) VISIBLE,
  INDEX (`user_id` ASC) VISIBLE,
  INDEX (`project_id` ASC) VISIBLE,
  INDEX (`category_id` ASC) VISIBLE,
  INDEX (`priority_id` ASC) VISIBLE,
  INDEX (`status_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`kind_id`)
    REFERENCES `lf_dawii`.`Kind` (`id`) ON DELETE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`user_id`)
    REFERENCES `lf_dawii`.`User` (`id`)ON DELETE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`project_id`)
    REFERENCES `lf_dawii`.`Project` (`id`)ON DELETE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`category_id`)
    REFERENCES `lf_dawii`.`Category` (`id`)ON DELETE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`priority_id`)
    REFERENCES `lf_dawii`.`Priority` (`id`)ON DELETE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`status_id`)
    REFERENCES `lf_dawii`.`Status` (`id`)ON DELETE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

